# Generated by Django 3.2.8 on 2021-10-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Инстаграм линия')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Инстаграм линия',
                'verbose_name_plural': 'Инстаграм линия',
            },
        ),
    ]
